name: pawis_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  analytics: ^2.0.3
  cloud_firestore: ^4.17.3
  firebase_analytics: ^10.10.5
  firebase_app_installations: ^0.2.5+5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo_noBG.png
    - assets/images/Logo_withBG.jpg
