// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiE24xk8V6jRzqgi_pFtzKwpoL05uRjFc',
    appId: '1:447923567655:web:f77906530fa95dcdac2202',
    messagingSenderId: '447923567655',
    projectId: 'project-pawis',
    authDomain: 'project-pawis.firebaseapp.com',
    storageBucket: 'project-pawis.appspot.com',
    measurementId: 'G-J3FPYES0J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHxD45EKLYHOZM7BVQ7iHyyvBe1wHZ3s0',
    appId: '1:447923567655:android:384343af12b83cd2ac2202',
    messagingSenderId: '447923567655',
    projectId: 'project-pawis',
    storageBucket: 'project-pawis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF-wgs3WZpB0OQe4uNQM2TfywdkY0G4sc',
    appId: '1:447923567655:ios:0cfc486595023aa2ac2202',
    messagingSenderId: '447923567655',
    projectId: 'project-pawis',
    storageBucket: 'project-pawis.appspot.com',
    iosBundleId: 'com.example.pawisApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF-wgs3WZpB0OQe4uNQM2TfywdkY0G4sc',
    appId: '1:447923567655:ios:0cfc486595023aa2ac2202',
    messagingSenderId: '447923567655',
    projectId: 'project-pawis',
    storageBucket: 'project-pawis.appspot.com',
    iosBundleId: 'com.example.pawisApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiE24xk8V6jRzqgi_pFtzKwpoL05uRjFc',
    appId: '1:447923567655:web:75e81d92947cffd7ac2202',
    messagingSenderId: '447923567655',
    projectId: 'project-pawis',
    authDomain: 'project-pawis.firebaseapp.com',
    storageBucket: 'project-pawis.appspot.com',
    measurementId: 'G-0WD24H5QRW',
  );
}
